### PR TITLE
:sparkles: hoc / not found routes

### PR DESCRIPTION
**Pull request by fabienjuif**
related to #14 

This is a first implementation of `not found` routes.
The next implementation (v2) should allow us to have multiple nested `not found` routes. This is quite necessary for conference-hall.

cc - @AFaugeras

### CODE REVIEW

**Comment by fabienjuif** [comment]
@frinyvonnick is it something you are interested by ?

**Comment by fabienjuif** [comment]
cc @bpetetot

**Comment by AFaugeras** [comment]
Works like a charm, thanks! :)

**Comment by fabienjuif** [comment]
You are welcome, feel free to ask questions in issues of our differents libs ;)

**Pull request merged**
